# Generated by Django 5.2.17 on 2026-10-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_decades', models.JSONField(blank=True, default=list)),
                ('preferred_languages', models.JSONField(blank=True, default=list)),
                ('discovery_level', models.CharField(choices=[('FAMILIAR', 'Familiar'), ('BALANCED', 'Equilibrado'), ('EXPLORER', 'Explorador')], default='BALANCED', max_length=10)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disliked_genres', models.ManyToManyField(blank=True, related_name='+', to='movies.genre')),
                ('preferred_genres', models.ManyToManyField(blank=True, related_name='+', to='movies.genre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
