# Generated by Django 5.2.17 on 2026-10-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_tmdblistcache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField()),
                ('signature', models.CharField(max_length=64)),
                ('discovery_level', models.CharField(max_length=10)),
                ('is_fallback', models.BooleanField(default=False)),
                ('degraded', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_run', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('FOR_YOU', 'Para vos'), ('HIDDEN_GEMS', 'Joyas para descubrir'), ('KEEP_EXPLORING', 'Continuá explorando')], max_length=16)),
                ('position', models.PositiveSmallIntegerField()),
                ('affinity_score', models.FloatField()),
                ('novelty_score', models.FloatField()),
                ('quality_score', models.FloatField()),
                ('diversity_score', models.FloatField()),
                ('exploration_score', models.FloatField()),
                ('popularity_penalty', models.FloatField()),
                ('final_score', models.FloatField()),
                ('popularity_bucket', models.CharField(choices=[('VERY_POPULAR', 'Muy popular'), ('POPULAR', 'Popular'), ('MEDIUM', 'Medio'), ('HIDDEN', 'Poco conocida')], max_length=12)),
                ('explanation', models.TextField()),
                ('generated_at', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.movie')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.recommendationrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'position'],
                'indexes': [models.Index(fields=['run', 'section', 'position'], name='snapshot_section_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_recommendation')],
            },
        ),
    ]
