# Generated by Django 5.2.17 on 2026-10-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKE', 'Me gusta'), ('DISLIKE', 'No me interesa'), ('WATCHED', 'Vista'), ('FAVORITE', 'Favorita'), ('WATCHLIST', 'Pendiente'), ('REMOVE_WATCHLIST', 'Quitar de pendientes')], max_length=16)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'type', '-created_at'], name='interaction_user_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie', 'type'), name='unique_user_movie_interaction')],
            },
        ),
    ]
