# Generated by Django 5.2.17 on 2026-10-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDBListCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('tmdb_ids', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
    ]
