# Generated by Django 5.2.17 on 2026-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_tmdblistcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='collection_tmdb_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='keyword_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
