# Generated by Django 5.2.17 on 2026-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_refresh_details_for_saga_and_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('display_priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='origin_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='providers_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_providers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tmdblistcache',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
